# 配置文件

[output]
path = 'output/{year}/{num}'
needCut = true

[proxy]
## proxy [socks5://][127.0.0.1:]<1-65535>;
## 协议：socks4, socks5, http, https
socket = ""
enable = false

[DMMApi]
apiId = ""
affiliateId = ""